1. Install macport from macports.org
 
2. Install prerequisites packages
~$ sudo port install cmake libsdl

3. Extract podo source
~$ tar xzf podo-src.tgz

4. Make shadow build directory
~$ mkdir build
~$ cd build
~/build$ 

5. Setting up PODO environment
~/build$ export PD_DIR=$PWD
~/build$ cd lib
~/build/lib$ ln -s ../../podo-src/lib/fonts
~/build/lib$ cd ..

6. Run demo
~/build$ cd demo/dvr
~/build/demo/dvr$ ./dvr
